import linked_list
my_list = linked_list.linked_list()
my_list.append(1)
my_list.append(5)
my_list.append(10)
my_list.append(15)
my_list.append(20)
my_list.display()
print(my_list.length())
my_list.erase(3)
my_list.insert(2,50)
my_list.display()
print(my_list.get(2))
my_list.set(4,25)
my_list.display()
